name: Drift Detection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  drift-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run drift detection
        run: |
          python -m src.drift_monitoring
